CREATE USER 'silver'@'%' IDENTIFIED BY 'demo666';
GRANT ALL PRIVILEGES ON *.* TO 'silver'@'%' WITH GRANT OPTION;
FLUSH PRIVILEGES;

-- MySQL Script generated by MySQL Workbench
-- Mon Apr 29 11:54:07 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema rigs
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `rigs` DEFAULT CHARACTER SET utf8 ;
USE `rigs` ;

-- -----------------------------------------------------
-- Table `rigs`.`coins_yield`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rigs`.`coins_yield` (
  `date` DATETIME NOT NULL,
  `coin_yield` DECIMAL(20,5) NULL,
  `bitcoin_price` DECIMAL(20,8) NULL,
  `coin_price` DECIMAL(20,8) NULL,
  `revenue` INT NULL,
  `electricity_costs` INT NULL,
  `profit` INT NULL,
  PRIMARY KEY (`date`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `rigs`.`revenue`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rigs`.`revenue` (
  `date` DATETIME NOT NULL,
  `coin` VARCHAR(45) NOT NULL,
  `revenue` INT NULL,
  `expected_revenue` INT NULL,
  `ratio` DECIMAL(20,4) NULL,
  PRIMARY KEY (`date`,`coin`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `rigs`.`report`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rigs`.`report` (
  `date` DATETIME NOT NULL,
  `bitcoin_revenue` DECIMAL(20,8) NULL,
  `revenue` INT NULL,
  `electricity_costs` INT NULL,
  `profit` INT NULL,
  PRIMARY KEY (`date`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rigs`.`miner_stats`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rigs`.`miner_stats` (
  `date` DATETIME NOT NULL,
  `coin` VARCHAR(16) NULL,
  `balance` DECIMAL(20,5) NULL,
  PRIMARY KEY (`date`,`coin`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rigs`.`rig_stats`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rigs`.`rig_stats` (
  `rigs_id` INT NOT NULL,
  `date` DATETIME NOT NULL,
  `gpus_offline` TINYINT(2) NULL,
  `online` TINYINT(1) NULL,
  `hash` INT NULL,
  `coin` VARCHAR(16) NULL,
  `power_draw` INT NULL,
  PRIMARY KEY (`date`, `rigs_id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
